service: sf-json-helper

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 3

functions:
  transform:
    handler: handler.handle

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux