frameworkVersion: '3'

service: sf-json-helper

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 3
  memorySize: 128
  timeout: 10  

functions:
  transform:
    handler: handler.handle
    architecture: arm64

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: python3

package:
  patterns:
    - '!node_modules/**'
